version: '3.9'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:13.4
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"




